version: '3.3'

services:

  node:
    build: ./edwin-api
    image: node:latest
    command: npm start
    container_name: edwin-backend-nodejs
    environment:
      - MARIADB_DATABASE=${maria_db}
      - MARIADB_USER=${maria_user}
      - MARIADB_PASSWORD=${maria_password}
      - MARIADB_HOST=${maria_host}
    ports:
      - '3030:3030'
    expose:
      - '3030'

  vue:
    build: ./edwin-frontend
    command: npm run build
    container_name: edwin-frontend-vue
    environment: 
      - BASE_URL=${base_url}
    ports:
        - 3000:80