version: '3.7'

services:

  node:
    build: ./edwin-api
    image: node:latest
    command: npm start
    container_name: edwin-backend-nodejs
    environment:
      - MARIADB_DATABASE=${maria_db}
      - MARIADB_USER=${maria_user}
      - MARIADB_PASSWORD=${maria_password}
      - MARIADB_HOST=${maria_host}
    ports:
      - '3030:3030'
    expose:
      - '3030'

    # vue:
    # build:
    #     context: ./frontend
    #     dockerfile: Dockerfile
    # container_name: edwin-frontend-vue
    # ports:
    #     - 3000:80