version: '3.3'

services:

  edwin-nodejs:
    build: ./edwin-api
    image: node:latest
    command: npm start
    environment:
      - MARIADB_DATABASE=${maria_db}
      - MARIADB_USER=${maria_user}
      - MARIADB_PASSWORD=${maria_password}
      - MARIADB_HOST=${maria_host}
    ports:
      - '3030:3030'
    expose:
      - '3030'

  edwin-vue:
    build: ./edwin-frontend
    ports:
      - '80:8080'
    expose:
      - '80'
    links:
      - edwin-nodejs